version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:8000 game_monitoring.wsgi
    volumes:
      - .:/app
    ports:
      - "8000:8000"