# Generated by Django 4.0 on 2021-12-08 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vgSales',
            new_name='Games',
        ),
    ]
