# Generated by Django 3.1.2 on 2021-12-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_vgsales_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
